### ISSUE TITLE
Tooltip styles

### ISSUE THREAD

**Issue by Manningham** [apigee-internal/apigee-stilo#1]
![screen shot 2016-09-27 at 5 57 05 pm](https://cloud.githubusercontent.com/assets/12063122/18897108/14e461b6-84dc-11e6-8ea9-5fe7e31920c3.png)
^ Current styles
![screen shot 2016-09-27 at 5 57 13 pm](https://cloud.githubusercontent.com/assets/12063122/18897107/14e43844-84dc-11e6-8169-3140e8e523ef.png)
^ Styles from ui.e2e.apigee.net

Border radius probably received from bootstrap, which we will no longer import directly into the component apps.

**Comment by wigahluk** [comment]
Bootstrap border was overwritten by local styles, but never changed on the main variable. New styles are now using 0 as the default. I'll look for feedback with the Apigee UX team and add the fix or close this. Thanks!

**Comment by wigahluk** [comment]
You should be able to see the now corners in 0.1.2
