### ISSUE TITLE
Hover states

### ISSUE THREAD

**Issue by Manningham** [apigee-internal/apigee-stilo#2]
List row action icons and links (eg: the product name field on API Products SPA which links to shoehorned UI) should have hover states.

**Comment by Manningham** [comment]
Also, there should be some more space between the action icons on the rows:
![screen shot 2016-09-27 at 5 57 42 pm](https://cloud.githubusercontent.com/assets/12063122/18897196/d0dccae8-84dc-11e6-8ee7-9fa2294ef9e8.png)
^Current^

![screen shot 2016-09-27 at 5 57 36 pm](https://cloud.githubusercontent.com/assets/12063122/18897201/dfe0ac62-84dc-11e6-915e-a5264dd529c7.png)
^Desired^

**Comment by wigahluk** [comment]
The previous styles where using glyphicons, which we are no longer using in the new version. The space needs to be fixed though.

**Comment by threeset3** [comment]
@Manningham @wigahluk What's the status of this issue?

**Comment by Manningham** [comment]
I think it was invalidated when we removed wrench's from the rows in favor of having a click anywhere on the row now goes to the detail view.  I'll close this issue.
